# Console & Logging Configuration
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Subsystem Dependencies
CONFIG_GPIO=y

# Stack & Heap Sizes
CONFIG_MAIN_STACK_SIZE=2048

# C++ Support
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_GLIBCXX_LIBCPP=y

CONFIG_LED_STRIP=y
CONFIG_I2S=y
CONFIG_WS2812_STRIP_I2S=y

CONFIG_I2C=y

CONFIG_CBPRINTF_FP_SUPPORT=y